CRF_GearScriptConfig : "{EC17EA82C390260C}Configs/Gearscripts/Standard/Modern/CRF_GS_RHSMSV.conf" {
 m_FactionWeapons CRF_Weapons "{629D042A71256530}" {
  m_AT CRF_Spec_Weapon_Class "{629D042A59FA7CCC}" {
   m_Weapon "{3FEEC75992196DAC}Prefabs/Weapons/Launchers/RPG18/Launcher_RPG18.et"
  }
 }
}