SCR_MissionHeader {
 m_sName "CRF RUSH93 Bridges Too Close"
 m_sAuthor "tanaKa"
 m_sDescription "BLU 3:2 OPF - These damn bridges are too close"
 m_sIcon "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sLoadingScreen "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sPreviewImage "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sGameMode "RUSH"
 m_iPlayerCount 128
 m_iStartingHours 12
 m_iMapMarkerLimitPerPlayer 120
}